# Generated by Django 5.1.2 on 2024-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guider',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='guider',
            name='service_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
