# Generated by Django 5.1.2 on 2024-10-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('guiders', '0002_alter_guider_age_alter_guider_service_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guide',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='guiders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='guiders.guider'),
            preserve_default=False,
        ),
    ]
