# Generated by Django 5.1.2 on 2024-11-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_rename_guide_guest_name_remove_guest_email_and_more'),
        ('guiders', '0002_alter_guider_age_alter_guider_service_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guiders',
        ),
        migrations.AddField(
            model_name='guest',
            name='guiders',
            field=models.ManyToManyField(related_name='guests', to='guiders.guider'),
        ),
    ]
